version: '3.9'

services:
  db:
    image: postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
